theme: jekyll-theme-cayman
show_downloads: true
url: "https://rgring.github.io/RumexWeeds"
title: RumexWeeds
description: >- # this means to ignore newlines until "baseurl:"
  The real-world dataset RumexWeeds targets the detection of the grassland weeds: 
  Rumex obtusifolius L. and Rumex crispus L.. 
  RumexWeeds includes whole image sequences with totally 5,510 images of 2.3 MP resolution and 15,519 manual bounding box annotations 
  as well as 340 ground truth pixels-wise annotations, collected at 3 different farms and 4 different days in summer and autumn 2021. 
  Additionally, navigational robot sensor points from GNSS, IMU and odometry are recorded.
github:
  zip_url: test.zip #ToDo!
